ModularBungalow/bungalowWeapons/revolver.dm, ModularTegustation/tegu_jobs/Voidtech/voidtech.dm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PackedStation/PackedStation.dmm, code/game/objects/effects/landmarks.dm
Adds an Office to Void Technicians, and fixes spawn points.
This is a Fix, and makes Voidtech feel less tacked on.
:cl:
add: Added Voidtech offices to Meta and Delta
fix: fixes spawnpoints for Voidtech adn Secretary
/:cl:
=> Voidtech office

code/__DEFINES/antagonists.dm, code/modules/clothing/spacesuits/hardsuit.dm, code/modules/uplink/uplink_devices.dm, code/modules/uplink/uplink_items.dm
TC increased to 30.
Holoparasites increased to 22 (was 18)
CQC Increased to 15 (was 13)
Sleeping Carp increased to 15 (was 13)
Ebow increased to 11 (was 10)
Romerol increased to 40 (was 25)
Makarov decreased to 6 (was 7)
Origami Kit decreased to 13 (was 14)
Space suit reduced to 3 (was 4)
Added Mining hardsuit for 6 TC, and fake Engineering for 5
Adds more TC to traitors to deal with buffed staff and voidtechs.
:cl:
add: Added engineering and mining hardsuits
balance: gives traitors 30 TC and changes costs to match
/:cl:
=> Traitor Changes

ModularBungalow/SecuritySpecialist/specialist.dm, ModularBungalow/bungalowWeapons/energy.dm, code/modules/projectiles/guns/energy/sniper.dm, code/modules/ruins/lavalandruin_code/techcult.dm
Swaps out the nukie sniper for a special laser disabler and laser one.
Stops security from having 1-hit de-limbing weapons while still having wetwork as an option.
:cl:
add: Added Security laser sniper
tweak: Changed the security kit to have Laser sniper instead of ballistics one
/:cl:
=> Changes the nukie sniper with a laser one

code/game/objects/items/devices/PDA/cart.dm
removes qm functions from hop cartridge
hop isnt the qm's boss anymore
:cl:
del: qm part of hop pda cartridge
/:cl:
=> removes hop qm cartdrige

_maps/map_files/Mining/Lavaland.dmm
Adds some minor medical equipment to the medical area of lavaland.
No one likes dead miners, this lets them get revived right there with minimal work.
Lavaland doctors don't need to go back and forth upgrading their gear
:cl:
tweak: changed lavaland mining medical
/:cl:
=> Lavaland medical area upgrades

ModularTegustation/tegu_jobs/Voidtech/voidtech.dm, code/game/objects/items/storage/belt.dm
Gives engineers a drill in their belt
It makes sense for lore reasons. everyone else, VTs and Atmos, still get their normal belts
:cl:
tweak: makes this make sense in the year 2550
/:cl:
=> Gives engineers, and only engineers a drill

ModularBungalow/Cloning/circuits.dm, ModularBungalow/Cloning/machine.dm, ModularBungalow/Cloning/trauma.dm, tgstation.dme
Cloners now require micro-lasers, with the incentive to upgrade being errors.
Each limb and organ has a base 25% chance to not spawn on t1 lasers, and it has a 2.5% chance to spawn a mild or severe trauma.
Chances decrease with tier, having it be 5% on organs and limbs and 0.5% on traumas at t5.
Cloners are a bit busted, this should make it so doctors can't just clone them, chuck them in cryo and be done with it. However, the cloner is still a viable option in emergencies such as gibbing or
excessive brute/burn damage
:cl:
add: cloner malfunctions
/:cl:
=> Cloner malfunctions

code/modules/surgery/organs/heart.dm
Ports https://github.com/tgstation/tgstation/pull/58016 over. I'll just quote that PR for the rest of this one:
This PR makes it so that people who have gone through the Muscled Veins experimental surgery will no longer suffer heart attacks or damage from having a dis-functional heart, since they don't need one.
This also negates the heart attack caused by things such as Penthrite overdose, and I imagine other poisons. I haven't tested all of them but I don't see why it would be different.
Whether intentional or a bug, this was an issue and discouraged the Muscled Veins surgery, since it meant you had to go through two surgeries (one of the augmentation and another one to remove the heart), to get it's benefits. This is both inconvenient and kinda dumb.
:cl:
fix: Heart failure no longer …
=>  A non-functional heart no longer causes heart attack if you have Muscled Veins

code/modules/clothing/gloves/miscellaneous.dm
Ports https://github.com/tgstation/tgstation/pull/58319 over. I'll just quote that PR for the rest of this one:
This PR makes it so that the Plasmamen Atmospherics Envirogloves aren't insulated.
The rest of the engineering envirogloves are insulated because both engineers and CE's normally use insuls, however, atmos techs shouldn't be getting insuls, so this seems like an oversight.
:cl:
fix: Atmospherics Envirogloves are no longer insulated.
/:cl:
=>  Atmospherics Envirogloves are no longer insulated. 

ModularTegustation/tegu_jobs/Voidtech/voidtech.dm
Title
VTs have to get into ruins, and allowing them to hack into powered ones more easily makes sense
:cl:
balance: gave void techs an engineering skillchip
/:cl:
=> Gives voidtechs an engineering skillchip

code/modules/clothing/spacesuits/plasmamen.dm
Ports https://github.com/tgstation/tgstation/pull/58318 over. I'll just quote that PR for the rest of this one:
This PR makes the Atmospherics Plasmamen Envirohelmet have the same max_heat_protection_temperature as the Atmospheric Hardsuit helmet. The description of the Atmospherics Envirohelmet has also been changed to reflect this, now having the same "Has thermal shielding." line at the end as the Atmospheric Hardsuit and Hardsuit helmet.
If you have a Plasmamen Envirohelmet 99% of the time you have easy access to an Atmospherics Hardsuit, so this is simply for the convenience of not having to take off your envirohelmet to get the full fire protection of wearing a Hardsuit and so that it's easier for meds to recognize you as a plasmaman from the helmet, rather than stripping you and …
=>  Atmospherics Envirohelmets now have the same fire protection as the Atmospherics Hardsuit Helmet

ModularTegustation/tegu_jobs/Voidtech/voidtechClothing.dm, ModularTegustation/tegu_locker_overwrites.dm, code/modules/clothing/suits/bio.dm
Buffs biosuits by doing the following:
Increases Laser resistance to 20%, from 0. (They're bright white fucking armor, generally very reflective they should be able to help a little bit with armor)
Reduces slowdown from 1 to 0.35
increases heat resistance from 0 to 500K
VT hardsuit slowdown decreased from 0.35 to 0.25
Increases bullet and laser resistance by 5 each.
Also the CMO finally gets their gun.
Finally Biosuits are fucking worth using.
:cl:
balance: Buffed Biosuit
fix: finally gave the CMO their rifle.
/:cl:
=> Buffs Biosuits and makes them usable over Hardsuits (and the VT hardsuit)

code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
Gives herald cloak FIRE_PROOF and LAVA_PROOF
Its a cloak you can only get from lavaland, it really should of been fireproof in the first place
:cl:
tweak: The Herald cloak no longer burns up
/:cl:
=> Gives herald cloak FIRE_PROOF

ModularBungalow/budgetcard/deptartementcard.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/game/objects/structures/crates_lockers/closets/secure/scientist.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, tgstation.dme
Head's closet spawn with their departemental budget  card in it.
It may be redundant considering you can spend your departemental budget trough your head's card.
But with a physical item, you can use these cards for machines like paystands, BEPIS or even buy things from vendors. You can also insert manually credits in this
More economical interractions and gimmicks.
:cl:
add: Added back departemental budgets cards ! 
/:cl:
=> Adding back budget cards in physical item

_maps/RandomRuins/SpaceRuins/forgottenship.dmm, code/game/objects/structures/ghost_role_spawners.dm, code/modules/jobs/jobs.dm
- Cybersun Crew and Captain will now show up in tracked playtime, under "Special" roles(ghost roles and such are all here).
- Cybersun roles will show important_info on spawn, if policy isn't set by the admins.
- Cybersun vault now has more stuff, most noticeably - 40.000 credits to make it a valuable target for the station, or extra funds for bribing/trading with the station in case you want to roleplay a bit.
- I mean, who doesn't want to flex their playtime?
- Admins should probably set policy themselves, but having nothing at all is just sad.
- As I said, le roleplay OR combat target for cargo. The credits are mechanically useless to the Cybersun, unless they use it for BEPIS, in which case they straight up give station free research, so there shouldn't be many balance concerns.
=> Tiny Cybersun tweaks

code/modules/modular_computers/computers/item/tablet_presets.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/7134
borgs won't have to go to the nearest med or sec console to check manifest
(they also used to have it until robot commands verb panel was removed and replaced with robotact)
=> [PORT] Gives borgs the crew manifest NTOS app

ModularTegustation/tegu_mobs/chaos_marine.dm, code/modules/mining/equipment/explorer_gear.dm, code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
removed the honk crystal because it makes miners unable to use their pkas(they sometimes also bring it up to the station and griff people with it)
transferred the chaos marine's armor stats to the heck suit (also gave it 10 more melee)
moved the chaos marine's chainsword to crusher loot
removed the antimagic scroll
nerfed the armor to ash drake armor stats (still spaceproof)
the chaos marine gave WAY too much good loot for a fight slightly more difficult then the ash drake(probably even easier if you don't use the crusher)
I'm bad at explaining things
=> nerfs chaos marine armor, buffs H.E.C.K. suit and removes the honk crystal

code/game/objects/items/melee/misc.dm, code/game/objects/items/stunbaton.dm
Partially ports vlggms/tegustation/pull/121 and vlggms/tegustation/pull/139
- Whips and Classic Batons now have special attack effects depending on the limb user is targeting: Targeting arm will disarm the opponent, targeting leg will knock them down, targeting torso or head will deal a good amount of stamina damage.
- Stun batons now check for melee armor before applying stun and stamina damage, so anything above 70 melee(like death squad armor) is practically immune to their effect.
- More interesting mechanics for combat, allowing for dynamic strategies depending on what is your primary goal in the fight.
- Stun batons felt like an overpowered combat mechanic that practically kills everything in 2 hits without any counter. This makes it so armored targets, such as security officers and …
=> Telescopic Batons and whips now have special effects for limbs; Stun Baton checks for armor.

code/game/objects/items/weaponry.dm, code/modules/uplink/uplink_items.dm
(change ported from https://github.com/tgstation/tgstation/pull/59909)
bats are the best melee weapon in game due to near guaranteed stunlock and only costs 5 wood
scarp playermin removed because I want to see it used/I want to use it myself
~~stun batons were nerfed making bats the best stun weapon(against heavily armored opponents)  and I don't think they should be~~
stunlocking bad
scarp changes aren't probably
=> nerfs bats and removes the player_minimum on scarp

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_electronics.dm, code/game/objects/structures/door_assembly.dm, code/game/turfs/open/floor.dm, tgui/packages/tgui/interfaces/AirlockElectronics.js
https://github.com/tgstation/tgstation/pull/61226
allows for the re/building of cycling doors
=> [PORT] The Cycling 2.0, Airlocks can now be built in game to cycle and named

ModularBungalow/altjobtitles/alt_titles.dm
Adds and changes a bunch of different security titles to fit better with the lore (that I just created). (Also, hopefully the senior titles don't break. I added a list behind a few of them to get the extra names in).
Tons of variety for the different roles is always a nice thing, especially if you want to express yourself more in your role. Also, Commander (navy) is in there for lore reasons.
:cl:
add: "Sergeant Officer" and "Intelligence Officer" as security titles.
tweak: Replaces "Sergeant" with "Security Sergeant", "Sergeant Major" with "Man-At-Arms" - "Security Major", and "Staff Sergeant" with "Chief Investigator"
/:cl:
=> Security Titles

_maps/map_files/AndromedaStation/Andromeda.dmm
Changes to the amount of hardsuit numbers on Syndicate Marine Corps.
All Bloodred Hardsuits have been removed.
Staff Officers, Pilot Officers and the Req Chief no longer get their special hardsuits.
The amount of Syndicate EVA hardsuits in the armory has been reduced to two.
All Cybersun hardsuits from the Armory have been removed.
The First Officer now gets a Cybersun Hardsuit
The Marines got a LOT of hardsuits, I tossed the balance in the total opposite way when I made this PR after marines won a grand total of 0 rounds.
Now Xenos can't last 10 minutes.
Of Course, this means that stealing the command hardsuits is now something that MPs can arrest for, alongside protecting the officers groundside.
:cl:
balance: changed the amount of hardsuits marines get from 24 total to 7
/:cl:
=> SMC Major Balance changes

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PackedStation/PackedStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm
Xenoarch is no longer a prototype at all. 
There's now a capsule on every map.
Moves Xenoarch out of the prototype realm and into reality.
:cl:
add: Added Xenoarch capsule to every map.
tweak: Swapped out the science chem lab on pubby (NOT the Chemist lab, the science chemistry lab) with a xenoarch lab.
/:cl:
=> The Xenoarch update we needed.

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
fixes #275 
i literally just copied the code from the other pr linked in the issue that was just one line that told the projectile who fired it. it seemed to work for me, but maybe someone else can test just to be sure
you probably shouldn't be able to shoot yourself on accident
:cl:
add: One line that stops mecha projectiles from hitting itself
/:cl:
=> Fixes mechs shooting themselves

code/modules/research/nanites/nanite_programmer.dm
Little known features of nanite programmers: whenever you say something like "nanites when" they respond: "When you code it!!"
Unfortunately, it has no cool down and can hear itself, so when putting mutiple station radios next to it, it spams the shit out of that message, and this can crash the server
:cl:
fix: Removed the ability for nanite programmers to crash the server.
/:cl:
=> Fixes crash bug

code/__DEFINES/obj_flags.dm, code/modules/clothing/head/hardhat.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/head/misc.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/spacesuits/_spacesuits.dm, code/modules/clothing/spacesuits/plasmamen.dm, code/modules/clothing/suits/bio.dm, code/modules/clothing/suits/utility.dm, code/modules/hydroponics/beekeeping/beekeeper_suit.dm
Allows plasmamen to wear hats on top of their helmets. They are purely cosmetic, so, if they have any kind of protection, it won't be used.
I made a define to make some exceptions, so plasmamen can't wear some things such as space suit helmets, the atmospherics firefighting helmet and security helmets, because they are limited and they shouldn't be used for cosmetic purposes.
It's mechanic is simple: you can wear any kind of headwear by having it in hand and clicking on your envirohelm, and remove it by alt+leftclicking it.
Here's a video showing the whole thing:
https://youtu.be/wuII64lIn0E
More cosmetic possibilities for plasmamen!
:cl:
add: a define to make headwear exceptions
add: allow plasmamen to wear things on their helmets
add: alt+click to take off the hat on the helmet
del: …
=> Plasmamen can wear hats

code/modules/mob/living/carbon/alien/special/alien_embryo.dm, code/modules/mob/living/simple_animal/hostile/alien.dm
Now chestbursting no longer gibs! (fucking FINALLY)
All the AI Xenos that got their health doubled in a patch have their health reduced
This was back when we used mixed PVE+PVP Syndiecorps.
:cl:
tweak: chestbursting now CHESTBURSTS and doesn't gib
balance: ai xenos used on rock and charlie station
/:cl:
=> Nerfs Chestbursting and AI Xenos

code/modules/clothing/spacesuits/hardsuit.dm
Reduces the slowdown of the miner hardsuit from 1 to 0.3.
Reduces the Laser and Energy stats to 0.
We have rockplanet in rotation, this helps alleviate some of the issues with that.
:cl:
tweak: tweaked miner suit to be faster
/:cl:
=> Miner Hardsuit no longer slow as fucking balls

code/controllers/subsystem/job.dm, code/datums/ert.dm, code/game/gamemodes/revolution/revolution.dm, code/modules/antagonists/ert/ert.dm, code/modules/antagonists/revolution/revolution.dm, tgstation.dme
Starts to overhaul the Revolution game mode.
THIS NEEDS TO BE TMED
I see rev problems boils down to one issue:
People just indiscriminately kill. There is no reprecussions for killing an innocent.
I will solve this by doing two things:
Part 1: Changing targets from All heads to Captain, HOS, HOP, Detective and Warden.
All heads already get sunglasses, and should get the strategic option of flashing for a stronger ally earlier on. They will likely get mindshielded fast. Capture them fast or you lose this oppurtunity.
RD, CE, QM and CMO should NOT be killed just for having bad luck. They don't even start mindshielded, nor are they "High Ranking". They are the 4th-7th in line for command and not security members
Part 2: Giving the dead a choice to respawn later in the round.
Revs tend to …
=> [NEEDS TM]Revolution Overhaul Part 1

_maps/map_files/RemoraStation/RemoraStation.dmm
Adds some airtight flaps to the cargo bay's conveyor belts leading into the cargo shuttle.
So the cargo bay doesn't depressurize when left open.
:cl:
add: Added airtight flaps to cargo on remora station.
/:cl:
=> Adds airtight flaps to cargo shuttle belt on remora station.

tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Takes the silicon's binary chat from the light mode and replaces the dark mode chat with the one in light mode.
(Will IN THEORY work, maybe wont(probably wont(this isnt gonna work is it(nope))))
This idea came from this pull request from TG: https://github.com/tgstation/tgstation/pull/33222
(Picture is from their pull request(in theory it should look like this while on dark mode instead of only light mode))
I dunno it just makes it more visible.
:cl:
tweak: Makes the silicon chat more visible.
/:cl:
=> Changes visibility of the silicon's binary chat.

_maps/map_files/RemoraStation/RemoraStation.dmm, code/modules/awaymissions/corpse.dm, code/modules/paperwork/paper_premade.dm
Adds a janitorial ruin in one of the asteroids on remora station. The story behind this is that a station was about to implode (for unknown reasons) and the janitorial staff reinforced their walls with plasteel, hoping that they would hold up for the explosion. Theres a little paper that is in the ruin too (maybe if i can get it to work)
Until I figure this out please dont merge
I dont know, its directly below the mining base so maybe they could have some fun with it.
:cl:
add: Added new ruin in mining base asteroid on remora station
/:cl:
=> Adds a janitor ruin on remora station

_maps/map_files/RemoraStation/RemoraStation.dmm
Adds some basic atmospherics to the toxin launching shuttle on Remora Station.
So the shuttle can regain atmospherics.
:cl:
add: Added atmospherics to Remora's toxin shuttle.
/:cl:
=> Adds atmos to Remora's toxin shuttle

code/controllers/subsystem/ticker.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_defines.dm
When someone joins as the AI round start, a shell will be created for them. 
Original PR: https://github.com/yogstation13/Yogstation/pull/10397
Thanks to the head coder for helping my tiny brain fix this.
The round is 1 minute in. Over science comms you hear the screaming of a robotic voice, "ROBO MAKE ME A SHELL SO I CAN DO SOMETHING"
This problem is no longer! The ai now has a shell from roundstart
:cl:
add: AI will have a shell roundstart.
/:cl:
=> Gives the AI a shell from roundstart.

code/game/machinery/computer/crew.dm
fixes issue where sleeping people show up dead on binary sensors.
[PORT OF TG 64157]
quality of life, plus sleeping people no longer are dead
:cl:
fix: sleeping people no longer show up dead on binary sensors
/:cl:
=> fix sleeping crew monitor bug

code/modules/mob/living/carbon/human/species_types/felinid.dm
Powergamers are using felinids for the speed, doesnt matter if you have 1% speed is still overpower cause you can just run your enemies, "but they recieve more damage" yeah try to hate someone tan run faster than you.
they are humans with tails/ears they dont need buffs that makes they nerfs nothing.
someone needs to make real nerfs to felinids if they want to make then faster, cause right now they are better than any race.
-less powergaming
-less fake felinids
:cl:
/:cl:
=> Removes the buffs that where giveng to felinids.

code/game/objects/items/toys.dm
(PORT OF TG #64389)
Lets monkeys pop balloons with foam darts. Bloons drop iron coins when popped this way.
:cl:
add: Monkeys can pop bloons and drop money from popping them. Now you can play bloons TD6 in ss13!
/:cl:
=> Bloons TD6 in SS13

ModularBungalow/NTSL/code/modules/scripting/Implementations/Telecomms.dm, ModularBungalow/NTSL/code/modules/scripting/Interpreter/Scope.dm
This PR attempts to complete the following goals: 
1. Fix the `broadcast` system (script-side) to actually function as intended.
2. Allow NTSL code blocks using process_signal() to optionally return two signal objects.
3. Added an optional argument to the signal constructor.
(Also I forgot to add 'monkey' to the language list in #527 , added it here. ooh ooh ah ah.)
**For point 1:** The broadcast function just was not working. It now is, you must create the signal object as its own variable in-script first. The broadcast function already was 'implemented', the function was designed to send a message but with control over the properties of the message from NTSL.
Example:
```
...
newsignal = signal("My legs have atrophied", 1355, "Aemil Ferrilinea", "Bartender");
broadcast(newsignal);
... …
```
=> a simulation, INSIDE, of a simulation! NTSL updates

_maps/map_files/Fermistation/Fermistation.dmm
Engineering part 2 electric boogaloo
Adds a suppermatter engine to Fermistation and moves the tesla to the south (tesla storage is now behind CE locked shutters)
This is good because the tesla engine had a tendency to loose midround and couldnt produce enough power on its own, making it so engineers always had to jury rig the system to run the engine.
You now have the choice to build either engine, adding the the variety of the map, while making it more accessible to more playstyles.
This update is also in anticipation of an atmospherics rework.
:cl:
add: El kreatura des supermatter engine
add: More maint areas near engineering
fix: some minor mapping things
/:cl:
=> Updating Fermistation part 8 Engineering rework

code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
Port of [Skyrat13 PR #550](https://github.com/Skyrat-SS13/Skyrat13/pull/550l)
The tumor shard now grabs the ghost and shoves it back into the lavaland mob.
Miner's dont have to wait for mob to get controlled again
:cl:
code: forces ghost to go into rezz'd elite fauna through E.grabghost
/:cl:
=> stupid simple fix

code/game/objects/structures/aliens.dm
Port of TGstation #64477
lowered the grow time limit from 15-20 seconds to 5-10 seconds
weeds can't grow in water now
documented the variables and procs
use the cooldown system
children weeds of the parent node will be destroyed on parent destroyed
weeds can still grow (just showing)
https://gyazo.com/e0e6b4ab35e0d7abd74981a7ddc976b2
weeds will die when their parent dies
https://gyazo.com/691f64e118a467b534fb1c5137684380
weeds finding a new parent
https://gyazo.com/14c17b365803a29e85f861c5d226cbf3
it feels awful clearing the xeno weeds at times, this should help that.
xeno weeds also feel really slow when growing, so this'll help xenos there.
🆑
tweak: xeno weeds will now be destroyed when their parent node is destroyed
balance: xeno weeds spread cooldown lowered from 15-20 seconds to 5-10 …
=> Xeno weed cahnges [PORT]

_maps/map_files/generic/CentCom.dmm, code/game/machinery/bounty_board.dm, code/game/machinery/buttons.dm, code/game/machinery/computer/camera.dm, code/game/machinery/defibrillator_mount.dm, code/game/machinery/flasher.dm, code/game/machinery/igniter.dm, code/game/machinery/lightswitch.dm, code/game/machinery/requests_console.dm, code/game/machinery/status_display.dm, code/game/objects/items/storage/secure.dm, code/game/objects/structures/extinguisher.dm, code/game/objects/structures/fireaxe.dm, code/game/objects/structures/mirror.dm, code/game/objects/structures/noticeboard.dm, code/game/objects/structures/watercloset.dm, code/modules/mining/aux_base.dm, code/modules/paperwork/ticketmachine.dm, code/modules/power/lighting.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/security_levels/keycard_authentication.dm, code/modules/vending/medical_wall.dm
If kirie or someone else dosent like it you can close it.
Adds directional variants to:
- pepper spray refills
- virus food dispensers
- wall-mounted flashes
- wall-mounted igniters (sparkers)
- defib mounts
- door buttons
- notice boards
- urinals
- wall safes
- light switches
- wall nanomeds
- fireaxe cabinets
- request consoles
- bounty boards
- mirrors
- entertainment monitors
- aux base monitor
- ticket machines
- tube lights
- small lights
- AI and evac screens
Reduces map file sizes, easier to use when mapping, helps when porting map things from tg, skyrat, and whatever other server has these.
=> The Wallening Approacheth: Adds directional variants to most wall mounts [PORT]

ModularBungalow/xenoarch/xenoarch_reward.dm, _maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/CasioStation/Casiostation.dmm, _maps/map_files/Fermistation/Fermistation.dmm, _maps/map_files/GalaxyStation/Galaxystation.dmm, _maps/map_files/GalaxyStation/Galaxystation_LVL2.dmm, _maps/map_files/PackedStation/PackedStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, _maps/map_files/RemoraStation/RemoraStation.dmm, code/modules/vending/medical_wall.dm, code/modules/vending/robotics.dm
Removes all health analyzers from maps.
This is a long time coming
They're not even available roundstart, now we're removing them from a lot of the maps.
:cl:
tweak: removed health analyzers from maps
/:cl:
=> Removes Health Analyzers

_maps/map_files/CasioStation/Casiostation.dmm
Moves a desk on casio, also adds in the cap bathrobe
the lawyer drobe was inaccessible
:cl:
tweak: tweaked lawyer office on casio
/:cl:
=> Fixes lawyer's office on casio

code/modules/research/designs/autolathe_designs.dm
Adds sci protolathe flags to syringes and droppers to sci protolathe.
Scientists are no longer forced to build autolathe in case droppers get missing from xenobio. It makes no sense for them to not be available to sci protolathe anyways. Also someone asked for it, so why not do that instead of telling them to code it themselves or cope.
:cl:
tweak: Bringing droppers and syringes designs to Science Protolathe
/:cl:
=> Update Sci Protolathe - Syringes and Droppers

code/controllers/subsystem/mapping.dm
Maprotation will now no longer pick the same map twice
More variety is always good
:cl:
tweak: tweaked maprotation
/:cl:
=> Maprotation will no longer pick the same map twice

ModularBungalow/mobs/apostle.dm, ModularBungalow/mobs/apostle_antag.dm, ModularTegustation/tegu_items/apostle_items.dm
- Nerfs apostles' rapture armor melee, bullets and laser armor. Slowdown has been slightly reduced to compensate.
- Nerfed damage from apostles' rapture weaponry.
- Apostle heretic gets a proper message as to what they are supposed to do.
- Fixes the deafening scream ability. It doesn't go through ear protection anymore.
- Nerfs overall damage dealt by several abilities.
- Removed separate apostle cooldown in favor of keeping just the revival one.
- White Night has more(800 --> 1000) damage on spawn, but converting people grants you less health buffs.
Makes it less disgusting to fight against.
:cl:
fix: White Night(apostle megafauna)'s deafening scream can't ignore ear protection anymore.
tweak: Updated round-end screen for apostles. 4 states of victory/defeat!
balance: Most WN's …
=> Nerf/tweak Apostle

ModularBungalow/mobs/megafauna/rockplanet/platinumangel/megafauna.dm
title
removing the ability for players to spawn a invincible megafauna is good for the game right? 
:cl:
fix: platinum angel is nolonger spawnable via gold xenobio extracts
/:cl:
=> fixes platinium angel being gold core spawnable

code/datums/mapgen/Cavegens/IcemoonCaves.dm, code/datums/mapgen/Cavegens/LavalandGenerator.dm, code/game/objects/structures/lavaland/geyser.dm, code/modules/vending/medical.dm
https://github.com/tgstation/tgstation/pull/58859
miners/chemists actually interacting with geysers
:cl:
add: Miners can now discover geysers with their mining scanner for a point reward! This will discover their type and mark that geyser (with type) on the GPS system.
del: removes the ClF3 geysers
add: Adds a very rare strange geyser that has a random reagent (maintpill/strange seed style)
balance: Geysers can now be activated with normal, cheap plungers
/:cl:
=> [PORT] Geyser rebalancing, gives miners points for discovering geysers

code/modules/admin/verbs/secrets.dm
"Anarch-communist" secret no longer deletes your equipment.
As funny as it is, some people were complaining that their precious armor or hat were being deleted.
:cl:
tweak: Anarcho-communist admin button no longer deletes your equipment.
/:cl:
=> Anarchy doesn't delete equipment

code/modules/client/preferences_toggles.dm
Makes it so the preference "Hear/Silence Ambience" is instead "Hear/Silence Ambient Sounds" and makes it so it doesn't stop ship ambience
It's kinda confusing if you see "silence ambience" when trying to turn off the ship rumble and it comes back on a bit later, so I think it saying "ambient sounds" is more accurate and less able to be confused by people. there's both "Hear/Silence Ambience" and "Hear/Silence Ship Ambience" and that may be confusing as well
:cl:
tweak: changed name of "Hear/Silence Ambience" to "Hear/Silence Ambient Sounds"
del: removed "Hear/Silence Ambience" stopping ship rumble
/:cl:
=> Change "ambience" preference

_maps/map_files/Mining/Asteroidbelt.dmm, _maps/map_files/Mining/Jungle.dmm, _maps/map_files/Mining/Lavaland.dmm, _maps/map_files/Mining/Rockplanet.dmm, _maps/map_files/Mining/Tidalmoon.dmm, _maps/map_files/PackedStation/PackedStation.dmm, _maps/map_files/TaliStation/TaliStation.dmm
adds GPS and tcomms to rockplanet
fixes the APC on rockplanet being connected to the SMES' input
adds oreboxes to tidal
adds a oxy can to asteroid belt
adds oreboxes and GPS to packed
also replaces some empty aidkits to full ones
🆑
add: adds GPS and tcomms to rockplanet
fix: fixes the APC on rockplanet being connected to the SMES' input
add: adds other misc stuff like oreboxes and GPS to maps missing them
/🆑
=> adds GPS and oreboxes to mining maps missing them

_maps/map_files/Mining/Asteroidbelt.dmm
Removes the axe from the asteroid mining base, and gives them proper O2 tank
Giving miners a fucking axe was an awful idea and honestly an oversight.
I wanted a fully functional mining station and went a little overboard.
:cl:
del: Removed axe from the asteroid base.
/:cl:
=> Removes the Axe from the asteroid base

ModularBungalow/Mining/rockplanet.dm, ModularBungalow/mobs/megafauna/rockplanet/arlem/megafauna.dm
Shifts around mob weights on rockplanet.
Also changes Arlem's bullets from hitscan to neotaser bullets
Well, hivebots were 10x more likely to show up than goliaths. This fixes that a little.
Also Arlem would literally instakill you. Now they no longer do so. They just knock you over.
:cl:
tweak: tweaked rockplanet spawns.
balance: Arlem no longer instakills you.
/:cl:
=> Rockplanet Mob Rebalance, and Arlem Nerf

code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/traitor/traitor.dm
Reduces the chance of mining traitor to 20%
This needs to be recoded to actually support other jobs like secretary who are okay as antag at 20% but when more than that are absolutely fucking stupid
Mining Traitors are honestly bad for the game.
Miner antag is boring as shit anyways, they just leave the station for like 50 minutes. 
IF they come back they are a god and if they don't then you lose a traitor.
This isn't being removed, nor will it be confined to the usual no job restriction like captain and HOS
Instead I'm cutting it back to 20% of what it was before.
:cl:
balance: Miners can only be traitors 20% of the time.
/:cl:
=> Kills Mining Traitor

ModularBungalow/bungalow_Weapons/Energy/sniper.dm, ModularBungalow/bungalow_Weapons/series/mining.dm, code/modules/projectiles/gun.dm
Adds a new gun variable to lock the miner guns to mining planets.
God, honestly this was planned for so fucking long.
These guns were NEVER designed to be used in the way they have before, where miners would mass buy them, and mass buy firing pins, and then fucking put regular pins in the mining guns.
This fixes it.
:cl:
add: Added new trait to where you cannot remove the firing pin from certain guns
balance: Miner guns cannot be used on station anymore.
/:cl:
=> Adds Pinlocked Trait to Miner Guns

_maps/map_files/CasioStation/Casiostation.dmm, code/datums/weather/weather_types/radiation_storm.dm, code/modules/events/radiation_storm.dm
Also makes the rad storm last longer
Makes the rad storms last longer, and also shields bar and kitchen as well as maintenance
Code from
https://github.com/tgstation/tgstation/pull/67058/files
Some people can't get into maints, they might as well go to the bar/kitchen for some bar RP for all of 3 minutes.
:cl:
tweak: adds bar and kitchen to the radiation shielding
tweak: Makes radstorms last longer
/:cl:
=> Rad Storm Minor tweaks

_maps/map_files/TaliStation/TaliStation.dmm
Fixes the Waste and Distribution pipes being connected together by a manifold that was placed ontop of both of them, and incinerator input on Talistation.
This PR closes issue #784 
This is my first ever PR. So i hope i didnt majorly destroy anything by accident.
>Before the edit
>After the edit
=> Fixes connected Waste and Distribution pipes on Talistation

ModularBungalow/clothing/hardsuits.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/neck/_neck.dm
the helmet light sprite wasn't set and the hardsuit doesn't have goliath plated sprites, both of which would turn the suit permanently invisible  
:cl:
fix: the compact mining hardsuit nolonger turns invisible if you turn on the helmet light or add goliath plates
fix: wearing a wig now hides the hair under it 
/:cl:
=> fixes the compact mining hardsuit sprites

_maps/RandomRuins/SpaceRuins/forgottenship.dmm, code/game/objects/structures/ghost_role_spawners.dm
Giving the Syndicate Forgotten shiprole some extra firepower in case they're invaded.
Total Additions:
1x Pump-shotguns
1x Surplus Rifle
2x Mg-90ls (In Pod)
Image:
Idef Buff PR cause me salty.
But seriously the Syndicate Cruiser feels lacking in defense, when it's likely that the Crew will come with the best of the best in gear if they're space exploring and fuck them over.
The issue of them using it in an offensive manner is entirely rules-based, and will be punished if they use the stuff to attack the station unless provoked anyways.
:cl:
add: Stuff for the Syndies Ship ghost role
/:cl:
=> An Ided Cybersunship Buff

ModularBungalow/bungalow_beacon.dm
fixes https://github.com/Quasar-13/Quasar-13/issues/786
fixes https://github.com/Quasar-13/Quasar-13/issues/781
:cl:
fix: cap's gun beacon now actually has the melter gun rifle
/:cl:
=> fixes cap's melter gun beacon choice
