_maps/map_files/PackedStation/PackedStation.dmm

:cl:
add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

updates da map

---

_maps/map_files/PackedStation/PackedStation.dmm

it just works
it just works
:cl:
add: it just works
add: it just works
del: it just works
tweak: it just works
balance: it just works
fix: it just works
soundadd: it just works
sounddel: it just works
imageadd: it just works
imagedel: it just works
spellcheck: it just works
code: it just works
refactor: it just works
config: it just works
admin: it just works
server: it just works
/:cl:

update 2 to packed

---

ModularTegustation/tegu_spaceruins.dm

fuck you github
:cl:
add: datum for teg ruin
/:cl:

makes a seperate fucking pull request for this

---

_maps/map_files/PackedStation/PackedStation.dmm

you can now make maracas go chick chikity boom
shout out to Chiemi#3132
:cl:
add: TOXINS
tweak: SERVICE
/:cl:

Adds toxins and reworks service on packed

---

ModularBungalow/bungalowchemistry/bungalowmutation.dm
tgstation.dme

Via Vae <3
Makes Mutation toxins craftable with the base one
It's cool
:cl:
add: Added new chem recipe
/:cl:

Added Extra mutation toxin

---

ModularBungalow/structurescapsules/capsules.dm
ModularBungalow/structurescapsules/structures.dm
_maps/templates/workplace_engineering.dmm

Adds Engineering workspace Capsule and thus fixes the issue with the blank capsule
Fixes an issue with workspace capsules, adds another one to use.
:cl:
add: Added engineering capsule
:cl:

Added the workspace capsule, Just need to look for anything to fix

---

ModularBungalow/structurescapsules/capsules.dm
ModularBungalow/structurescapsules/structures.dm
_maps/RandomRuins/SpaceRuins/derelict6.dmm
_maps/RandomRuins/SpaceRuins/intactemptyship.dmm
_maps/RandomRuins/SpaceRuins/oldAIsat.dmm
_maps/RandomRuins/SpaceRuins/onehalf.dmm
_maps/templates/shelter_cabin.dmm
tgstation.dme

Makes RTGs very common, and adds in a new capsule.
Makes RTGs more common in space and adds in a new shelter.
Gives Void Tech a low-level tech they can bring back to make, and gives them an actual house along with the bathouse.
:cl:
add: Added new capsule house
tweak: make RTGs more common
/:cl:

Cabin capsule and RTG boards and rarity.

---

_maps/RandomZLevels/SnowCabin.dmm
_maps/map_files/generic/CentCom.dmm

Adds in special Surgeon General Office and Intelligence Office
Just minor RP things.
:cl:
add: Added new Centcom areas
/:cl:

Adds Centcom Offices

---

ModularBungalow/ruins/interdyne.dmm
_maps/map_files/KiloStation/KiloStation.dmm

De-rusts Kilo station, but not the maints or anything
Fuck Kilostation. this makes it manageable
:cl:
tweak: Made kilo not shit
/:cl:

Fixed the fucking map

---

README.md

Reverts Kitsunemitsu/KirieStation#38
I have no clue why, but this keeps fucking everything up

Revert "Updates the readme"

---

tgstation.dme

temporarily removes interdyne

---

tgstation.dme

Reverts Kitsunemitsu/KirieStation#45
Issue may have been fixed.

Re-adds interdyne

---

_maps/map_files/BoxStation/BoxStation.dmm

Makes the maint monsters more bearable on box
We don't have a maint monster map, and this is a great change tonewbox
:cl:
add: Added door locks to the dangerous rooms
add: Added aux kitchen to locker rooms
tweak: moved the russians
/:cl:

Maint monster changes

---

ModularBungalow/bungalowWeapons/energy.dm
ModularTegustation/tegu_captaingun.dm
ModularTegustation/tegu_security_code/tegu_starter_gear.dm
code/modules/projectiles/guns/energy/energy_gun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/sniper.dm
code/modules/projectiles/guns/energy/special.dm
code/modules/projectiles/guns/energy/stun.dm

Changes all the names of guns to a consistent naming scheme
:cl:
tweak: tweaked gun names so that they more closely resemble IRL names
/:cl:

Names guns cooler

---

code/modules/jobs/job_types/geneticist.dm

Changes documentation to the geneticist to be more accurate to our server.

Quickfix to the Geneticist

---

code/modules/jobs/job_types/geneticist.dm

You wouldn't fucking believe how awful our headcoder is, just look at this shit

How am I this fucking dumb

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/MetaStation/MetaStation.dmm

Fixed Map bugs on Meta and Box station
On Meta Genetics no longer get double apc 
On Box the captain can finally use his bathroom after it was walled off, now it has a new look
:cl:
Replaced: Replaced the captain's bathroom door with a white airlock named bathroom on Box
Removed: the second medical APC in genetics on meta
/:cl:

Box and Meta stations bug fixes

---

code/datums/components/bloodysoles.dm
code/datums/quirks/good.dm
code/game/objects/effects/decals/cleanable.dm
code/game/objects/effects/decals/cleanable/humans.dm

Basically a port of this : https://github.com/tgstation/tgstation/pull/57085
- Makes now a difference between old and recent fights. Meeting fresh blood may be worrying. 
- Stops people having their boots (and sometimes suit) bloody because you dared to walk on a bloody footstep that was 95% transparent.
tweak: Blood dries with time.
tweak: Blood sticks less to boots. No longer a footprint should dirty your shoes after being washed recently.
/:cl:

Blood dries with time and is less sticky to boots.

---

_maps/map_files/PhoboStation/PhoboStation.dmm
_maps/phobostation.json

We need this station, It's so bad and so amazing
This map is the pinnacle of bad design. I want it.
:cl:
add: Added Phobos Station
/:cl:

Phobos Station

---

code/modules/reagents/chemistry/reagents/other_reagents.dm
code/modules/surgery/surgery_helpers.dm
code/modules/surgery/tools.dm

This makes surgery tables way preferrable to Stasis beds and changes Cautery's second function to drill 
Makes Surgery rooms better
:cl:
tweak: tweaked the cautery to be better
balance: rebalanced stasis beds and surgery
/:cl:

Medical Overhaul V1 (Surgery Quickfix)

---

ModularTegustation/tegu_captaingun.dm
ModularTegustation/tegu_jobs/Voidtech/voidtech.dm
_maps/map_files/BoxStation/BoxStation.dmm
code/game/machinery/stasis.dm

Weekly Hotfix

---

ModularBungalow/cyberorgans.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/techweb/all_nodes.dm
code/modules/surgery/organs/eyes.dm
tgstation.dme

Adds cybernetic organ quirks
They replace your organs with basic cybernetics
Yeah that's it
Oh cybernetic eyes too, they're weak to flashes same as moths so moths can't powergame with them
Uh... uh... idk
Seems fun I guess
Plus now EMPs are somewhat viable as a weapon against anyone insane enough to use these quirks
:cl:
add: cybernetic organ quirks
add: basic cybernetic eyes
/:cl:

Cybernetic Organ Quirks

---

code/modules/clothing/under/accessories.dm

like always i did a opsie
this fix the opsie
:cl:
fix: fixed the names of the armbands, 
/:cl:

this should fix the name problem of the armbands.

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Makes Remora's halls smaller
:cl:
tweak: Remora has 3 wide halls now
/:cl:

Ensmallened Remora's Main halls

---

code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Rebalances all the T3 chems to be slightly more annoying to make
They're a little too easy to make, and slightly too powerful when mixed together.
:cl:
tweak: tweaked C3 chems
/:cl:

Rebalances 5 C3 Chems

---

ModularTegustation/README.md

I came here to laugh at PRs, only to see my own shitty PRs' effects.
It isn't, but it is good for my eyes.
Not needed, not touching anything game-related.

Ports updated readme

---

code/__DEFINES/DNA.dm

Ports https://github.com/tgstation/tgstation/pull/58618 over. I'll just quote that PR for the rest of this one:
The DNA.dm file's #define statements which aren't numerically ordered are now alphabetically ordered. 
and Autonomy, which was missing from the list of mutation definitions, is now also added.
I shall lay a curse upon all who make long #define lists without organizing them in a sensible manner.
And also having Autonomy's definition is nice I guess.
:cl:
spellcheck: Ordered all things not in numerical order by alphabetical order in the DNA.dm file
code: Adds the missing #define statement for the Autonomy mutation in the DNA.dm file
/:cl:

 DNA.dm file Spring cleaning

---

_maps/RandomRuins/JungleRuins/jungle_nest.dmm
_maps/RandomRuins/JungleRuins/jungle_pizzawave.dmm
_maps/RandomRuins/JungleRuins/jungle_seedling.dmm
_maps/RandomRuins/RockRuins/rockplanet_clock.dmm
_maps/RandomRuins/RockRuins/rockplanet_clowncrash.dmm
_maps/RandomRuins/RockRuins/rockplanet_cult.dmm
_maps/RandomRuins/RockRuins/rockplanet_dangerpod.dmm
_maps/RandomRuins/RockRuins/rockplanet_pioneer.dmm
_maps/RandomRuins/RockRuins/rockplanet_pod.dmm
_maps/RandomRuins/RockRuins/rockplanet_tradepost.dmm
_maps/RandomRuins/RockRuins/rockplanet_wizard.dmm
code/datums/ruins/jungle.dm
code/datums/ruins/rockplanet.dm

adds around 10 new ruins to rockplanet and jungle.
more ruins are always awesome!
:cl:
add: Added more ruins to rockplanet and jungle
/:cl:

A large amount of ruins

---

config/admins.txt

tildw
idk
:cl:
del: kirie she doesnt exist anymore
/:cl:

remmeoeves kiriw

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

next time i will put everything in draft until i finish
this fixes some power problems and fix a missing cable in SCI.
:cl:
added herobrine
remove herobrine
added a single coil cable
/:cl:

ChimeraStation more fixes part 2

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

less power problems. 
remove some walls.
reinforced some windows.
*shrug
:cl:
add: Added wires
/:cl:

ChimeraStation Fixes part 3

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/PackedStation/PackedStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

Remora fix, again

---

_maps/map_files/PackedStation/PackedStation.dmm

fixed #132
Having space in the hallway makes me sad :(

Fixed space in Engi hallway

---

_maps/_basemap.dm
_maps/map_files/Mining/Tidalmoon.dmm

Tidal Moon is fixed

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Makes remora better by changing the megafauna
The Dragon was fucking hilarious though.

Remora upgrade

---

strings/names/death_commando.txt
strings/names/japanese_prefix.txt
strings/sillytips.txt
strings/tips.txt

funny text changes

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

less ugly maint
Atmos and sec/chapel maint was very empty, no anymore!
:cl:
add: Added  things in maint. dont know
/:cl:

better maint for ChimeraStation

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

ahhhhhhhhhhhhhhhhhhhhhhhhhhhh
get out of my head
:cl:
tweal: things
fix: fix
/:cl:

fixes fixes fixes fixes fixes

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

makes some hallway looks better, remove some ugly stuff and ands things in main
Ugly stuff: no
prettly stuff: yes
:cl:
tweak: i really dont know what to put here
/:cl:

ChimeraStation, better looks in some places, and small fixes

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

more stuff 
more stuff
:cl:
/:cl:

ChimeraStation, less empty maint, minor changes in kitchen and botany also tourist. 

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Remora Feat. Tesla; A shocking experience!
We need to actually use this instead of me just spawning it in every round
:cl:
add: Tesla To remora
/:cl:

Remora station 15 MV Edition

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

rework in atmos
there was a lot of fucking pipes, this "fix" that by making some pipes more "simple" and removing useless(?) shit,  making it "easy" to see what the fuck is happening. i still have no idea what the pipes do.
:cl:
add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Chimera: Atmos got a small/middle? rework. 

---

_maps/shuttles/emergency_raven.dmm

title
:cl:
fix: The Raven Cruiser emergency shuttle has the right console now
/:cl:

Raven Cruiser shuttle console fix

---

code/modules/mob/living/life.dm

Attempts to port https://github.com/OracleStation/OracleStation/pull/331
Test merge
Actually makes Sudden Sleep Disorder real
:cl:
add: Added SSD sleep
/:cl:

[TM] SSD sleep

---

_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/PackedStation/PackedStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

fixes #182 
couldn't find the duplicate light in the 7th pic
didn't change most of the rwalls in packed perma
couldn't find a disconnected pipe at packed cryo pods
:cl:
fix: The medkit on Remora bridge in now accessible
fix: There is now a stacking machine in Remora disposals
tweak: Packed's cryo pod room nolonger has rwalls
fix: Remora perma nolonger has a extra camera attached to nothing
fix: Delta Science nolonger has floating sinks and showers, they have been moved somewhere else
/:cl:

fixes most issues in #182

---

_maps/map_files/ChimeraStation/ChimeraStation.dmm

fixes
fixes 
:cl:
fix:fix:fixed
/:cl:

fixes robotics in Chimera.

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Title
allows you to call alot more places(not that anyone uses them) or AIs to present themself and chat with people "face to face"
:cl:
add: Remora Station has alot more holopads now
/:cl:

adds more holopads to Remora

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/MetaStation/MetaStation.dmm

box dorms cam and pharmacy light switch fix
also deleted a dupe light switch on Meta northwest solar array
Delta command equipment

reported map bugs

---

code/game/objects/items/cards_ids.dm
code/game/objects/items/devices/PDA/PDA.dm
code/modules/modular_computers/computers/item/computer.dm

vlggms/tegustation#152
:cl:
qol: Using credits on a PDA, Laptop, or Tablet now inserts the credits into the contained ID card, if there is one
/:cl:

[PORT] Money put into PDA/Tablet will go into ID, if there is one in it.

---

code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
code/modules/projectiles/projectile/bullets/dart_syringe.dm

BeeStation/BeeStation-Hornet#1447 and the ones after it
Somewhat works

[PORT] Cat Butcher changes

---

code/modules/admin/IsBanned.dm

They've spoken
:cl:
del: Underage people
/:cl:

Keeps kids out of the game

---

code/game/objects/items/storage/backpack.dm

Duffelbags have been slightly buffed
Maybe someone will actually fucking use these then
:cl:
tweak: reduced slowdown and increased capacity of duffels
/:cl:

Buffs Duffles

---

code/modules/admin/IsBanned.dm

(F) Cubato Tomson has messaged CentCom, "hello Cale Johnson i just wnat to report how great time i have in the station, clen halways,fair sec team,medbay is full on healing the crew, and cap manage all at his best. i like so much that i decide to go to space to find my famlly..bye for ver my friends at centcom" at Bridge.
:cl:
fix: Underage people are now properly banned.
/:cl:

Fernando's a failure, can't have shit in Detroit. 

---

code/modules/uplink/uplink_items.dm

Reduces Scarp pop req to 13

---

_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

deleted unused pipes and wire near grav gen on remora
gave the captain the right pinpointer on remora
moved a light switch on meta

small map fixes

---

code/modules/clothing/suits/cloaks.dm
code/modules/mining/machine_vending.dm
code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm

ports 3 things from https://github.com/tgstation/tgstation/pull/56472 (title things and adds ice hiking boots to vendor)
makes pubby mining less horrible and the icemoon part of tidal

gives ash drake armor cold resistance also gives icemoon megafauna gps

---

_maps/RandomRuins/JungleRuins/jungle_seedling.dmm

gives the seedling ruin a area

---

code/datums/ai/monkey/monkey_behaviors.dm

https://github.com/tgstation/tgstation/pull/57149

[PORT] Monkeys no longer rip apart machines from the inside

---

code/__DEFINES/achievements.dm
code/datums/achievements/boss_achievements.dm

title
goat king was removed along time ago

Removes goat king achievement

---

code/datums/components/chasm.dm

https://github.com/tgstation/tgstation/pull/60004/

[PORT] wisps no longer fall in chasms

---

code/datums/components/creamed.dm

https://github.com/tgstation/tgstation/pull/57789

[PORT] You can now clean pies off of your face in the sink

---

_maps/map_files/PubbyStation/PubbyStation.dmm

moved ever so slightly to be less in the way for generic modifications 
less in the way for generic modifications

moves a pubby engine room scrubber

---

code/modules/reagents/chemistry/reagents/toxin_reagents.dm

I don't really like that someone could have all of their scars removed involuntarily, 
Theres already a way for someone to voluntarily remove their scars in the character menu
idk

removes carpotoxin scar reaction

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/PackedStation/PackedStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

Fixes one APC on box, one wire in packed and the medhud scanners on remora

Map Fixes again

---

ModularBungalow/Kiriechem/reagent.dm
ModularBungalow/Kiriechem/reagentselector.dm
ModularBungalow/Kiriechem/recipes.dm

If you're gonna bring back old chems, it's a good idea to spell them properly. 
This adds the i.
It isn't.
:cl:
spellcheck: adds the i
/:cl:

Adds the i

---

code/datums/achievements/misc_scores.dm
code/modules/reagents/reagent_containers/pill.dm

[PORT] Fixes maint pill score not being tracked

---

.vscode/settings.json
code/modules/research/designs/mecha_designs.dm

Title, only the disabler is still available at the mechfab
~~Didn't bother to test this~~
people have expressed their distaste to robotics being able to print weapons without the permission of sec

Restricts mech weapons to sec prolathe

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm
code/modules/asset_cache/asset_list_items.dm

Put a mining equipment vendor on Box
rewired Remora's gravgen room slightly
gave the chaplain a button to close their shutters on Delta

small map changes

---

code/modules/admin/verbs/secrets.dm
code/modules/clothing/spacesuits/plasmamen.dm
code/modules/clothing/under/jobs/Plasmaman/medsci.dm
tgui/packages/tgui/interfaces/Secrets.js

Port from #vlggms/tegustation/pull/106
Adds an "Anarcho-Communism Mode" admin secret to the game.
It practically makes everyone "equal" by giving them AA and similar outfits.
Also makes the economy so _freaking stable_ that everything costs much less.
https://www.youtube.com/watch?v=h_T7bD4pAlE

Mother Anarchy loves her sons.

---

code/_globalvars/lists/flavor_misc.dm

https://github.com/tgstation/tgstation/pull/61243

[PORT] Byond member ghost recolors can now have hair + accessories

---

ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm

A quick port from vlggms/tegustation/pull/141
This, in theory, fixes adv hypnoflash to make it work properly.
Bugs are, obviously, bad.
:cl:
fix: Advanced hypnoflash now should work correctly.
/:cl:

Fixes(?) advanced hypnoflash

---

_maps/RandomRuins/AnywhereRuins/golem_ship.dmm

Ports vlggms/tegustation/pull/140
Changes the free golems' ship to something "absolutely" new.
As far as I am aware, I should give the credit to [WhiteSands](https://github.com/Whitesands13/Whitesands) for this nice design.
The Current(Old) ship is just... sad.
The new design looks more like a ship than an empty box with random crates.

Updates golem ship

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Mining/Jungle.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm

removed a duplicate virology door button on box
replaced the butcher with the cat surgeon on box
added a landmark to jungle mining so the public shuttle works
removed all unlocked air alarms that probably shouldn't of been unlocked on pubby

more map changes

---

code/modules/mob/living/carbon/human/examine.dm

https://github.com/tgstation/tgstation/pull/61260
>More visible characterization for roleplay purposes, you can now tell if that character with white hair is supposed to be an old lady or an anime schoolgirl.

[PORT] Adds visible age to examine_more

---

code/game/objects/items/toy_mechs.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

Ports tgstation/tgstation/pull/58630
The codebase will now properly compile on 514s versions of Byond.
Not really for the game, but 514 is used by a lot of contributors and I'd prefer if we didn't have to downgrade.

Makes codebase compatible with 514

---

ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm

That's right. It had wrong item inside and I fixed it.
Also made it so only the kit items can be stored in this box to avoid *gaming*.
Bug fix.

Fixes mad clown kit

---

code/__DEFINES/combat.dm
code/datums/components/embedded.dm
code/datums/elements/embed.dm
code/datums/wounds/burns.dm
code/game/machinery/Sleeper.dm
code/modules/surgery/burn_dressing.dm
code/modules/surgery/healing.dm
tgstation.dme

https://github.com/tgstation/tgstation/pull/58682
https://github.com/tgstation/tgstation/pull/56637
https://github.com/tgstation/tgstation/pull/59534
QoL I guess

[PORT] Tend Wounds and Debride Infection surgeries now estimate how long you have left to finish

---

code/game/objects/structures/noticeboard.dm
code/modules/paperwork/clipboard.dm
code/modules/paperwork/paper.dm
tgui/packages/tgui/interfaces/Clipboard.js
tgui/packages/tgui/interfaces/NoticeBoard.js

https://github.com/tgstation/tgstation/pull/59389
https://github.com/tgstation/tgstation/pull/57289
papers can now be viewed on both

[PORT] TGUI clip and notice boards

---

ModularBungalow/altjobtitles/alt_titles.dm
_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

Fixes a spelling error
Minor map fixes
:cl:
fix: fixed wrong areas in boxstation
fix: fixed perma on remorastation
fix: fixed an issue with the "sergent" alt title for the warden. it is now properly named
/:cl:

Multiple minor fixes

---

code/modules/projectiles/projectile/special/neurotoxin.dm

Says it on the tin
Xenos got crushed in 5 minutes.
:cl:
balance: stamina damage now instantly stamcrits
/:cl:

Updates Neurotoxin to insta-down

---

code/modules/projectiles/projectile/special/neurotoxin.dm

Reverts Kitsunemitsu/KirieStation#328
this was a horrible idea

Revert "Updates Neurotoxin to insta-down"

---

_maps/map_files/PackedStation/PackedStation.dmm

Security checkpoint is gone, cryo room has been moved to dorms
Don't touch maps you don't maintain
:cl:
add: Packstation has been sligtly remodeled
/:cl:

small packed changes

---

ModularTegustation/tegu_mobs/chaos_marine.dm
code/game/objects/structures/icemoon/cave_entrance.dm
code/modules/mining/lavaland/necropolis_chests.dm

I'm bad at explaining things
chaos marine's chainsword damage has been lowered from 30 to 15
armor penetration lowered from 50 to 30
block chance removed
fireball wand from ashdrake loot removed
bubble's spellblade replaced with ninja shoes(no-slip+-1 speed slowdown)
(I couldn't think of anything better to give both in rarity and usability) 
miner weapons that more or less is only given to kill crew with is bad?

nerfs chaos marine's chainsword and replaces bubble's spellblade for ninja shoes

---

config/maps.txt

Chimera is now Admin only.
Chimerastation is our resident highpop map.
This is a good thing and also a bad thing.
It's good because it's really nice to have a highpop map. 
But it's bad because it's votable.
Now that the map folder is cleared out, I will be moving chimera to the designated highpop map that admins can launch for when that happens.
:cl:
server: Chimerastation has been moved to being admin only.
/:cl:

Chimera is now admin only.

---

_maps/map_files/RemusFacility/RemusFacility.dmm

It's one tile big, but it's still a sec cell for cringe people
It's been requested multiple time
:cl:
add: Added security Cell to remus
/:cl:

Adds a sec cell on remus

---

_maps/map_files/RemusFacility/RemusFacility.dmm

Swaps the AKs out for T-12s and Tommy guns
Right now, soldiers are better than literally everyone else by like 6-7 times.
this should mitigate that a little.
Now they get 3 ARs and if more soldiers join they get 3 tommy guns.
LORE REASONS!
:cl:
add: Added T-12 and Tommy guns into remus
add: Added in research console
/:cl:

Swaps guns out, adds in research console. 

---

ModularBungalow/clothing/smc.dm
code/modules/clothing/suits/armor.dm

Adds descriptions to the vests in accordance with the lore.
Keeping the lore consistent across the game and discord is good.
:cl:
add: Changed and added to the descriptions of many vests.
add: Vests edited: Bulletproof, Slim, "Alt", Detective, Syndicate, and Black Mesa Sec Guard.
/:cl:

Edits Descriptions of Vests

---

ModularBungalow/altjobtitles/alt_titles.dm

Adds one more alt title for CMO
Just in case someone wants to dedicate time teaching to others
:cl:
add: Added new alt title
/:cl:

Adds Medical professor Alt title

---

ModularTegustation/tegu_mobs/chaos_marine.dm

Port of vlggms/tegustation/pull/136 + some edits.
Buffs the sword a bit(not old OP numbers).
Right now the fight is rather easy and you can easily tank damage with crusher and drake suit.
Now, this wouldn't be the case and loot will correspond to the fight difficulty, hopefully.

Chaos marine buff

---

code/_onclick/hud/movable_screen_objects.dm

https://github.com/tgstation/tgstation/pull/57177
I like being able to move the action buttons

[PORT] Fixes action button movement not working

---

code/modules/projectiles/guns/energy/laser.dm

Changes some laser rifle names to fit with lore I guess
fitting with lore is pog
:cl:
add: changes the melter from l304 to l204 and the retro lasgun (the second most recent gun) to l304 from 204
/:cl:

change a few names real quick

---

ModularBungalow/displaycase.dm
_maps/map_files/PubbyStation/PubbyStation.dmm
tgstation.dme

A long, long time ago, there was a captain shotgun.
It was an objective and everything.
Pubby is the "Classic SS13" map.
Let's give it what it deserves.
:cl:
tweak: replaces the captain's gun in Pubby with a shotgun version
/:cl:

Adds in more Captain display cases, adds the shotgun into Pubby

---

code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm

https://github.com/tgstation/tgstation/pull/63034
https://github.com/tgstation/tgstation/pull/58060
I don't even know if heretic is in rotation

ports 2 heretic changes from tg

---

_maps/map_files/RemusFacility/RemusFacility.dmm
code/game/objects/items/storage/belt.dm

Gives the Administrator a Nagant revolver on Remus Facility
Well, They don't get a unique gun. Thought that this would be a good time.
:cl:
add: Added nagant to the administrator
tweak: tweaked syndicate ruin loot
tweak: tweaked the bandolier to hold more ammo types
/:cl:

Gives the Administrator a nagant

---

ModularTegustation/tegu_mobs/the_claw.dm

Forgot to do this in #399 
Read original PR.
It's just a fix.

Gives Claw actual hands

---

code/modules/jobs/job_types/!casio/blueshield.dm

Does what it says on the tin.
This role is sensitive, and requires you to follow the station rules.
:cl:
tweak: Blueshield is now a whitelist role.
/:cl:

Whitelists blueshield

---

_maps/map_files/CasioStation/Casiostation.dmm

How did I forget this?
:cl:
add: Adds fire alarms to casio
/:cl:

Adds firealarms to casiostation

---

code/modules/jobs/job_types/!casio/blueshield.dm
code/modules/jobs/job_types/!casio/ntcaptain.dm
code/modules/jobs/job_types/!casio/ntleader.dm
code/modules/jobs/job_types/quartermaster.dm
code/modules/jobs/jobs.dm
code/modules/mining/mine_items.dm
code/modules/vending/security.dm

Adds berets to the command vendor
Swaps some metabolisms around
Might fix the Casiostation captain
Just minor tweaks.
:cl:
tweak: tweaked metabolisms
tweak: tweaked command vendor things
tweak: added pistol to all mining lockers roundstart
/:cl:

Tweaks 30/12/21

---

interface/stylesheet.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss
tgui/packages/tgui/constants.js

I would rather tear my eyes out than have yellow command again.
Actually, it's almost the same colour as the admin log colour. But I hate the colour yellow with a passion.
:cl:
tweak: Command chat is now blue
/:cl:

Swaps command chat to Silver, as god intended.

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Does what it says on the tin.
They didn't have one
:cl:
tweak: Pubby Xenobio now has a grinder
/:cl:

Adds Grinder to pubbystation Xenobio

---

code/modules/clothing/suits/cloaks.dm
code/modules/mining/equipment/explorer_gear.dm
code/modules/mining/lavaland/necropolis_chests.dm

Nerfs all armor, removes basically all laser and Energy resistance, and replaces the ninja shoes with Jone
I want lavaland back. This is the first part, I still have to nerf
:cl:
balance: Nerfs all armor. Removes ninja shoes
/:cl:

Lavaland Nerfs V1 - Armor

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Fixes some minor issues on Remora Station.
-Fixes overlapping lattices on solars
-Fixes a tile of an asteroid that was missing.
-Changes the solar lattices to nearstation tiles.
Just some QoL
:cl:
fix: fixed some oversights on Remora station.
/:cl:

Fixes minor mapping issues on Remora Station.

---

_maps/map_files/Mining/Tidalmoon.dmm

Adds a tomb teleporter to tidalmoon.
I thought I'd want one, Lavaland has one
:cl:
add: Added tomb worlds teleporter to Tidalmoon
/:cl:

Adds Tomb Worlds to Tidalmoon

---

code/datums/mapgen/biomes/_biome.dm

Adds more variety to jungle mob spawning without changing the frequency
Sick of mooks and mega arachnids. It's time to get wacky.
:cl:
tweak: tweaked mob spawning in jungle biomes
/:cl:

Jungle Mob Changes

---

ModularBungalow/altjobtitles/alt_titles.dm

Removes deputy as sec alt-job (sorry van, but it had to be done) to try to fix the galaxy problem.
Adds a new CMO alt-title to check if that's why it's broken.
Fixes, fixes, fixes!
:cl:
fix: fixed deputy
fix: Moves CMO alt-title to senior in an attempt to fix a bug
/:cl:

Testfixing the Alt-jobs

---

_maps/RandomRuins/admin/cael.dmm
_maps/RandomRuins/admin/drekar.dmm
code/datums/ruins/admin.dm
tgstation.dme

Adds support for admin maps.
Xan made an admin map, and I made one a long time ago. 
:cl:
add: Added support for admin maps
/:cl:

Admin maps

---

_maps/RandomRuins/admin/drekar.dmm

Fucking fixes an issue
fix
:cl:
fix: fixed linter
/:cl:

I have to make a whole PR for this

---

code/modules/mob/living/silicon/ai/freelook/eye.dm

By examing the AIs eye as a ghost you can see it's laws
May or may not work, will test tommorrow
Port of:https://github.com/tgstation/tgstation/pull/58346
QoL
:cl:
tweak: Ghosts can see the AIs laws by examining it's eye.
/:cl:

Ghosts can observe ai laws through its eye.

---

code/modules/mob/living/silicon/pai/pai.dm

You can now emag a PAI to remove its master and their DNA from it, similar to emaging a borg.
Tested 👍 
More stuff for the poor PaI
:cl:
add: PaI's can now be emagged
/:cl:

You can now emag a PAI [TG Port]

---

ModularBungalow/clothing/underwear.dm

im dumb. (fix for real)

---

ModularBungalow/bungalow_beacon.dm
code/game/objects/structures/crates_lockers/closets/secure/security.dm

willard broke it
:cl:
fix: Fixed beacon issue
/:cl:

Beacon Fix

---

_maps/RandomRuins/IceRuins/icemoon_underground_techcult.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_techcult.dmm

Read title
Before: 
After: 
Its a fix for the icons.
:cl:
fix: Fixed techcult ruins computer frame icon being off
/:cl:

Fixes techcult ruin computers.

---

.vscode/launch.json
code/modules/recycling/sortingmachinery.dm
tgui/packages/tgui/interfaces/DestinationTagger.js

Port from yogstation pull request: 13082
Less shiddy tagmaster
:cl:
tweak: makes destination tagger use nice tgui instead of shitty Topic() that had no formatting
/:cl:

Introducing the TagMaster 3.0! Converts the TagMaster 2.2 to use TGUI [PORT]

---

ModularBungalow/ruins/interdyne.dmm
_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/CasioStation/Casiostation.dmm
_maps/map_files/CasioStation/Casiostation_old.dmm
_maps/map_files/Fermistation/Fermistation.dmm
_maps/map_files/GalaxyStation/Galaxystation.dmm
_maps/map_files/Mining/Tidalmoon.dmm
_maps/map_files/PackedStation/PackedStation.dmm
_maps/map_files/RemoraStation/RemoraStation.dmm

removes some duplicate latices and catwalks on the same tiles on some maps.
runtime fixes.
:cl:
fix: fixed runtimes across some maps
/:cl:

fixes some runtimes of duplicate lattices/catwalks on maps

---

_maps/map_files/CasioStation/Casiostation.dmm
_maps/map_files/CasioStation/Casiostation_old.dmm
_maps/map_files/ChimeraStation/ChimeraStation.dmm
_maps/map_files/GalaxyStation/Galaxystation.dmm
_maps/map_files/PackedStation/PackedStation.dmm

fixes more runtimes
runtimes
:cl:
fix: fixed runtimes again
/:cl:

r u n t i m e s

---

code/modules/admin/topic.dm
code/modules/jobs/job_report.dm
tgui/packages/tgui/interfaces/TrackedPlaytime.js

ports https://github.com/tgstation/tgstation/pull/56799
ask X
:cl:
/:cl:

ports: Re-adds the admin button to let them exempt players from job exp requirements.

---

code/modules/events/spacevine.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm

ports : https://github.com/tgstation/tgstation/pull/64363 (vine have a animation)
https://github.com/tgstation/tgstation/pull/64382 (mannitol taste sweat)
:cl:
/:cl:

ports 64363 and 64382

---

dependencies.sh
tools/bootstrap/python37._pth
tools/bootstrap/python_.ps1
tools/requirements.txt

From quick test all our helper scripts work fine on 3.7.
Why 3.7.9 instead of latest 3.7.12 ? Embed zips for these versions are missing from python.org ftp. (They apparently do not ship binaries for security-fix only releases)
:cl:
add: Python upgraded to 3.7.9
/:cl:

Bumps bootstrapped python to 3.7.9

---

_maps/map_files/generic/CentCom.dmm

read title
"WHY WONT THE FUCKING CODE WORK?"
:cl:
fix: fixed nukies codes
/:cl:

fixes nukies getting weird codes (maybe)

---

code/__DEFINES/economy.dm
code/controllers/subsystem/economy.dm

https://github.com/Skyrat-SS13/Skyrat-tg/pull/1996
paycheck.
i dont like to work for free, do you?
:cl:
/:cl:

ports https://github.com/Skyrat-SS13/Skyrat-tg/pull/1996 (paycheck)

---

_maps/RandomRuins/JungleRuins/jungle_techcult.dmm
code/modules/ruins/lavalandruin_code/techcult.dm

Read title
More jungle ruins.
:cl:
add: Added techcult ruin to jungle planet.
/:cl:

Adds jungle techcult ruin.

---

ModularBungalow/bungalow_beacon.dm
ModularBungalow/clothing/storage.dm
code/modules/jobs/job_types/!blacksite/deathsquad.dm
code/modules/jobs/job_types/!blacksite/ertcommander.dm
code/modules/jobs/job_types/!blacksite/ertengineer.dm
code/modules/jobs/job_types/!blacksite/ertmedic.dm
code/modules/jobs/job_types/!blacksite/ertsecurity.dm
code/modules/jobs/job_types/!blacksite/ntleader.dm
code/modules/jobs/job_types/!blacksite/ntmarine.dm

Fixes beacons to work as intended
Beacons :b:roke
:cl:
fix: fixed beacons
/:cl:

Fixes beacons

---

_maps/map_files/Fermistation/Fermistation.dmm

Ye ole quality of life updates and a bunch of fixes.
100% isnt gonna work.
Fermi
:cl:
add: More clutter because i hate cleanliness.
add: More maint tunnels for your walking convenience
del: Herobrine
fix: Bunch of shutters, airlocks and buttons (hopefully)
fix: Arrivals uhm, works now.
fix: Fixed the spider and moonshine
/:cl:

Updating Fermistation part 6

---

.github/workflows/ci_suite.yml

please for the love of god, don't delete shit in the checks if you don't know what they do/have no reason to delete them

readds a something to the ci suite workflow

---

ModularBungalow/altjobtitles/outfits.dm
code/modules/jobs/job_types/captain.dm

Should change the Commodore's backpack to the green one (that I made) and changes the captain's shoes from brown sneakers to laceups. (I believe this should change it across all things that are based on the captain).
:cl:
tweak: changed cap's shoes to laceups
tweak: changed Commodore's backpack to the new green one
/:cl:

Captain/Commodore Fixes

---

tgstation.dme

fixes span merge

---

code/game/objects/items/robot/robot_items.dm

After getting Gamered super hard, we decided to change this.
Removing a 1 click stun.
:cl:
tweak: Borg fist now knockdowns instead of paralyzes
/:cl:

Borg hardstun nerf

---

_maps/RandomRuins/SpaceRuins/asteroid5.dmm
_maps/RandomRuins/SpaceRuins/derelict5.dmm
_maps/map_files/CasioStation/Casiostation.dmm
_maps/shuttles/building_mechanic.dmm

Mechanics on Packed needed their shuttle to be able to go to more places
Also I forgot fucking fuel tanks on Casio.
:cl:
tweak: tweaked Casiostation, Added more mechanic docks
/:cl:

Mechanic Ship upgrade and Casio fixes

---

ModularBungalow/clothing/parade.dm

Changes the Rear Admiral's combat jacket from 25 bomb protection to 100.
Uh, i was requested to do this by kirie to fix an oversight since the admirals uniform should protect from gibbing.
Changelog
🆑
tweak: Admril's combat jacket is bombproof now.
/🆑

No more gibbing the admirals

---

_maps/map_files/PackedStation/PackedStation.dmm

Fixes some areas, runtimes, walls missing and other things on packed.
Runtime go brr
:cl:
fix: fixed a few things on packed station.
/:cl:

Some packed station runtime fixes and other things.

---

ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
code/modules/projectiles/projectile/bullets/pistol.dm

Makes the SOCOM fire a modified 10mm.
It finally implements 10mm as a properly used cartridge.
:cl:
tweak: made the SOCOM fire 10mm.
balance: made 10mm do 35 damage but have 20 AP to make it unique. (also changed the other special ammos if anyone wants to use them for something)
/:cl:

Mk23change

---

code/controllers/configuration/entries/comms.dm
code/controllers/subsystem/redbot.dm
code/datums/world_topic.dm
code/modules/admin/sql_ban_system.dm
tgstation.dme

Adds functions required by status cog of the discord bot.
Provides also "Who" and "Adminwho" to the bot.
Provides some more info about status of the server, as well as allowing custom notifications for in game events or bwoinks.
I am too sleepy to do this.

Status Module functions for Discord Bot

---

code/modules/clothing/glasses/_glasses.dm

I changed the debug glasses to be indestructible since they are debug items
Debug item shouldn't burn in lava and stuff
🆑
tweak: Added Lava proof, Frozen proof, acid proof and indestructible to the debug glasses.
/🆑

Debug Glasses!

---

code/modules/jobs/job_types/!packed/gooncargo.dm
code/modules/mob/living/carbon/alien/humanoid/humanoid_defense.dm
code/modules/projectiles/projectile/special/neurotoxin.dm

Also includes one line fix for Cargo tech
I am supposed to be on break and still had to do this.
Fucking hate Xenos. I literally would remove them aside from the funky gamemodes but Improve not remov
I'm sick of Xenos, honestly.
:cl:
balance: rebalanced neurtoxin
balance: rebalanced tackle
/:cl:

Xeno nerfs (Again)

---

_maps/map_files/RomulusFacility/RomulusFacility.dmm

See title
Checks won't fail maybe?
Nothing players care about

Fixes romulus description missing quotes 

---

_maps/map_files/Fermistation/Fermistation.dmm

More changes, more toil
Who am i to judge what is good or bad, i am but one man.
:cl:
add: mostly cameras 
tweak: tweaked the fabric of the universe
balance: moved the captains xeno egg to xenobio, it was funny while it lasted
fix: fixed a few things with flex seal
/:cl:

Updating Fermistation part 10 i take this brick and i place it next to this brick

---

_maps/map_files/RemusFacility/RemusFacility.dmm
code/datums/mapgen/biomes/_biome.dm
code/modules/jobs/job_types/!terragov/outpost/scientist.dm

Messy Fix, so we can play Remus again.
Remus is cool, but needed this.
Still needs a rework
:cl:
add: Added Syndicate and NT to Remus
/:cl:

Adds NT and Syndicate bases to Remus 2, very messily

---

_maps/map_files/Fermistation/Fermistation.dmm

Why are we still here
Just to suffer?
:cl:
tweak: every night
add: i can feel my leg
add: and my arm
balance: even my fingers
del: the body ive lost
del: the comrades ive lost
code: wont stop hurting
/:cl:

Updating Fermistation part 11 maint fixes

---

code/modules/jobs/job_types/!casio/ntcaptain.dm

Adds a navy backpack to the navy captain (tested on local, worked fine)
He had a blue one before that looked shit in his uniform.
:cl:
add: gives the navy cap a navy backpack
/:cl:

navy captain fix

---

ModularBungalow/altjobtitles/outfits.dm

Adds the entirety of the BNI Intelligence Agent's outfit. He has a rank pin, a chiappo, and most important of all, a full BNI uniform. Very Fashionable.
New outfits for outfit-less senior titles is neat.
:cl:
add: BNI Intelligence officer senior title outfit
/:cl:

BNI Intelligence Officer

---

code/modules/admin/sql_ban_system.dm

I want to get rid of that awful href:
Looks better I guess.
:cl:
server: sets new ban notice
/:cl:

Polishing ban notice

---

SpacemanDMM.toml
code/__DEFINES/_tick.dm
code/__DEFINES/qdel.dm
code/__DEFINES/spaceman_dmm.dm
code/__DEFINES/vv.dm
code/_compile_options.dm
code/controllers/subsystem/garbage.dm
code/datums/datumvars.dm
code/game/world.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/view_variables/reference_tracking.dm
code/modules/admin/view_variables/topic_basic.dm
code/modules/admin/view_variables/view_variables.dm

Mirrors TG commits aiming to switch to auxtools over extools, enabling the game to be compiled on byond versions 514.
Tested locally, fixes the "Failed to locate [randomshithere]" that originate from using extools with versions 514, that were hanging up deployment.
Fixes up naked bug apparently from what I have seen so far, therefore not forcing players to choose between hitting reconnect button or enjoying naked characters..

Nuke extools

---

ModularBungalow/vending_machine_edits.dm

Adds the black beret into the secdrobe (Tested on local, worked fine)
Extra drip options are always good
:cl:
add: sec black beret to secvend
/:cl:

Adds Black Beret to Sec vendor

---

ModularBungalow/altjobtitles/alt_titles.dm
ModularBungalow/altjobtitles/outfits.dm

Adds a new Geneticist senior title and outfit for said title. Tested on Local, works fine
More outfits are cool (and pap told me to)
:cl:
add: Outfit for Freak of Genetics
add: Senior Title "Freak of Genetics"
/:cl:

Geneticist, New

---

code/_onclick/hud/parallax.dm
code/game/objects/items/devices/radio/headset.dm

https://github.com/tgstation/tgstation/pull/62656
https://github.com/tgstation/tgstation/pull/61341
qol
:cl:
tweak: You can drag a headset onto yourself to open the menu.
/:cl:

[PORT] Headset mousedrop like PDA

---

code/modules/clothing/outfits/standard.dm

Changes CC Commander outfit to be more betterer
Full green CC commander with gloves and carapace is VERY noice.
:cl:
tweak: Changes cc commander to give it gloves, a green carapace, and a navy backpack
tweak: changes spec ops officer's under to use the gold officer uniform (because he had the SENIOR AGENT one before, very wrong).
/:cl:

CC Commander update

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Adds a ranger suit into pubbystation for the QM.
It's here, let's use it. It'll be cute
:cl:
add: Added QM's ranger duster to pubby 
add: Added Captain's bathrobe to the same map.
/:cl:

The QM's ranger Duster

---

_maps/map_files/RemoraStation/RemoraStation.dmm

Moves Janitor closet and opens medbay up
Janitor being in maints is never a good idea, that area is now a hobo den
:cl:
tweak: tweaked remorastation minorly
/:cl:

Remora updates

---

_maps/map_files/Fermistation/Fermistation.dmm

fixes power, probably
good for stopping angry engineers
:cl:
add: cables
add: also some more fluff items around the map, minor shibbang, you know how it is.
/:cl:

Updating Fermistation part 12 pain edition

---

code/datums/materials/basemats.dm
html/changelogs/Kalesonki-PR-626.yml

Fixes https://github.com/Bungalow-13/Bungalow-13/issues/617
Bugfix that solves the issues with autolathe, credits go to CRITAWAKETS from /tg/. Closes #617
Fixes autolathe not accepting plastic, allowing for printing materials using plastic.
:cl:
fix: Autolathe has been talked to and disciplined, taken into submission it now will stop being eco-terrorist and accept plastic sheets.
/:cl:

Autolathe now accepts plastic

---

code/modules/clothing/spacesuits/miscellaneous.dm

Adds the old version of the BNI officer's jacket as a separate item.
Jenny asked for it and it does look cool in it's own right.
:cl:
add: Old BNI jacket and Beret using old detective jacket and sec officer beret sprites.
/:cl:

Jacket thing

---

strings/tips.txt

Kinda needed to explain this.
Explains policy
:cl:
add: Added new tip
/:cl:

Adds new tip

---

ModularBungalow/Mining/rockplanet.dm

Rockplanet no longer has lavaland megafauna.
Rock needs it's own set of megafauna, of which it has two so far, with at least two planned.
:cl:
balance: No more lava megafauna on rock
/:cl:

No more Rockplanet megafauna

---

ModularBungalow/medicine/Kiriechem/mixer.dm
ModularBungalow/medicine/Kiriechem/reagent.dm
ModularBungalow/medicine/Kiriechem/reagentselector.dm

Part 4 of me de-shittifying Kiriechem.
This adds in the third and hardest table, where our best medicines and poisons lie.
Kiriechem was started as a good idea with bad execution.
This fixes everything, I swear.
:cl:
balance: Made Kiriechem less CBT
/:cl:

Kiriechem V4 - Tables 1 and 3

---

_maps/map_files/Fermistation/Fermistation.dmm

Bugfixes, its always bugfixes.
It just is, ok?
:cl:
add: Small QoL stuff
del: Cloning. Genetics is bigger in its place now. Nothing is replacing the lack of cloning for now.
tweak: airlocks and firelocks in a couple places
/:cl:

Updating Fermistation part 13 mister bones' wild ride

---

_maps/map_files/CasioStation/Casiostation.dmm

Expands kitchen and adds hallway doors to bar, hydro and kitchen
Adds more glockroaches to maint and de-shittified the transfer area, solars and the commissary
Casio is slowly getting better and better.
Let's keep it up
:cl:
fix: fixed casio map issues
/:cl:

Casio V5: Updating service (again)

---

ModularBungalow/medicine/Kiriechem/mixer.dm
ModularBungalow/medicine/Kiriechem/reagent.dm

1 line bug fix with Selenic Helioside in Kiriechem
Rebalances chems to do more or less genetic damage.
:cl:
fix: fixed helioside
balance: balanced some kiriechems
/:cl:

Fixes bug with Helioside, Rebalances some Kiriechems

---

code/game/machinery/firealarm.dm
code/game/machinery/newscaster.dm
code/game/objects/items/devices/radio/intercom.dm

yes
dirs begone
:cl:
add: Makes more stuff directional
/:cl:

Fire alarm, Intercom, and newscaster directionals

---

_maps/map_files/generic/CentCom.dmm

title
❤️ 
:cl:
add: Added a heart to the nanotrasen meeting area
/:cl:

makes the nanotrasen meeting area ( i think that is it's name ) be a heart

---

ModularBungalow/mobs/megafauna/rockplanet/platinumangel/items.dm

fixes plat angel's flashlight turning the helmet invis by removing it
:cl:
fix: platinum angel's helmet nolonger turns invis after turning the flashlight on 
/:cl:

fixes plat angel's helmet flashlight

---

_maps/map_files/TaliStation/TaliStation.dmm

adds intercomms, and news things.
:cl:
add: added things in walls. im in your walls.
/:cl:

Talistation 1.1v

---

_maps/RandomRuins/IceRuins/icemoon_underground_clockwork.dmm
code/datums/ruins/icemoon.dm

Adds Clockwork Knight to Icemoon.
The armor associated was unobtainable, so it's been added here.
:cl:
add: Added Clockwork Knight to Icemoon.
/:cl:

Adds Clockwork Knight to icemoon

---

_maps/map_files/TaliStation/TaliStation.dmm

bugfixes.
bug fixes.
:cl:
KIRIE YOU NEED TO SETUP THE AUTO CHANGELOG
/:cl:

Talistation v1.1b

---

_maps/map_files/TaliStation/TaliStation.dmm

directional stools
:cl:
MAKE THE CHANGELOG BE AUTO, GODDAMIT
/:cl:

TaliStation v1.1c

---

_maps/map_files/PubbyStation/PubbyStation.dmm

change some areas.
DO YOU KNOW HOW MUCH I HATE THAT UNSHADOW WALL IN MAINT!?
:cl:
tweak: areas in Pubby
/:cl:

Fixes some area problems in PubbyStation

---

code/__DEFINES/maths.dm
code/modules/mob/mob_movement.dm

https://github.com/tgstation/tgstation/pull/63058
idk
:cl:
balance: Diagonal movement is now slightly faster
/:cl:

[PORT] Makes diagonal movement euclidean

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/TaliStation/TaliStation.dmm

makes all tools be in the correct position.
fixes wrong area in box
minor changes in box and pubby. small ones.
eh
:cl:
add:  added some walls
fix: fixed wrong area in box.
/:cl:

Minor changes to box, pubby and talistation

---

code/modules/surgery/healing.dm

I just remembered this
:cl:
fix: fixes burn woundtending with health analyzer saying brute
/:cl:

fixes burn woundtending with health analyzer saying brute

---

_maps/map_files/TaliStation/TaliStation.dmm

change some minor stuff.
I LIVE IN YOUR WALLS.
:cl:
tweak: tweaks
/:cl:

TaliStation v1.1e? 

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/TaliStation/TaliStation.dmm

removes the double firedoors in pubby.
fix a button in tali.
makes the SM sat in tali 1 tile bigger.
I HATE DOUBLE FIREDOOR. FUCK THOSE.
:cl:
/:cl:

Removes Pubby double airlocks and fix a thing in talistation.

---

ModularBungalow/clothing/coat.dm

Gives paps outfit armor and the ability to wear gun i think.
Pap will beat me with a mop if i don't do this :p
:cl:
add: Changed the armor to be based on armor so pap can actually use it properly.
/:cl:

Adding armor stuff to the coc outfit.

---

code/modules/antagonists/wizard/equipment/soulstone.dm

The cultist soulstones will now work on ghosted cultists and give you their soul... erm, someone elses soul i guess?
If a cultist decides to ghost, their body should jsut go to waste and should be able to make a ghost an artificer or somethin.
:cl:
balance: cultist soulstone works on catatonic cultists now!
/:cl:

cult soulstones work on catatonic cultists

---

_maps/map_files/TaliStation/TaliStation.dmm

move some pipes, removes some rwalls and put some windows.
less shitty map
:cl:
/:cl:

bugfixes for talistation

---

ModularBungalow/clothing/coat.dm
ModularBungalow/clothing/helmet.dm
ModularBungalow/clothing/under.dm

Some HOP clothing had some awful names. This fixes them.
:cl:
fix: fixed some names
/:cl:

HOP Clothing name fix

---

_maps/map_files/RomulusFacility/RomulusFacility.dmm

Makes Chemistry less CBT on Romulus
Complaints, complaints and more complaints. 
This will quell it
:cl:
tweak: moved chem lab on romulus
/:cl:

Adds chem lab to Romulus

---

_maps/map_files/Fermistation/Fermistation.dmm

badabing badaboom but again.
fixes atmos mostly.
air is nice.
:cl:
add: some paper bins i guess
del: those double atmos pipes, yay
/:cl:

Fermistation v14 probably the last part 2

---

ModularBungalow/mobs/the_claw.dm

Claw no longer attacks people in the Death Squad faction with his ultimatum attack.
Slightly changed how AI attacks.
Fixed a bug and made NPC controlled Claw slightly more difficult to fight against.
:cl:
fix: Fixed Claw attacking itself with the ultimatum ability.
tweak: Claw AI now dashes slightly more often.
/:cl:

Fix claw attacks

---

ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
ModularBungalow/clothing/helmet.dm

Nerfs the fucking rocket launcher rifle and fixes helmet paths.
Hotfix
:cl:
balance: balanced fire rate of the rocket rifle
fix: fixed pathing of sprites. I know who the retard was that coded the paths this way, it was me. I still languish over it.
/:cl:

Fixes path regarding helmets (and unatomized weapon nerf)

---

ModularBungalow/Mining/rockplanet.dm
ModularBungalow/mobs/megafauna/rockplanet/platinumangel/megafauna.dm
_maps/RandomRuins/RockRuins/rockplanet_blooddrunk.dmm
_maps/RandomRuins/RockRuins/rockplanet_platinum.dmm
_maps/map_files/Mining/Tidalmoon.dmm
code/datums/ruins/rockplanet.dm
code/game/objects/items/devices/gps.dm

title
🆑
tweak: readds goliaths and hivelords to rockplanet
fix: fixes more stuff about plat angel and gives it a GPS signal
add: adds blood-drunk miner to rockplanet
/🆑

adds blood-drunk miner to rockplanet, readds goliaths and hivelords and changes some other misc stuff

---

code/datums/looping_sounds/machinery_sounds.dm

grav gen is quieter now
:cl:
tweak: grav gen is quieter
/:cl:

makes gravity gen be shut

---

code/modules/jobs/jobs.dm

The Commander and Admin were renamed without this being changed
Bugfix
:cl:
fix: Site Commander and Site Administrator can now be played from latejoin.
/:cl:

Kepler Hotfix

---

_maps/map_files/Fermistation/Fermistation.dmm

Ass blast USA, fixes some stuff, including genetics and some other things.
You know, you walk out the map editor. You see someone that you know, and they ask you how the map is, and you just have to say that the map fine, when its not really fine, but you just can't get into it because they would never understand.
:cl:
add: revamped the pharmacy a bit, added shutters too
fix: the maint transit tube
fix: genetics access
fix: a bunch of doors and buttons
/:cl:

Fermistation v15 epic hotfix

---

_maps/map_files/CasioStation/Casiostation.dmm
code/modules/projectiles/guns/energy/energy_gun.dm

Adds more guns to the Casio Armory, proper guns. This is a military station, it makes sense for the armory to be filled with weapons of expected quality. This includes:
3 Tactical Eguns
2 L704 Laser Rifles
1 L504 (Prototype) Laser Rifle
3 Riot Shotguns
Shotgun Shells
And Nonlethal Grenades
Tested on Local, works great.
The Casio armory was... very, very underequipped. The whole crafting your own guns gimmick was... ok? but it left the station horribly undefended, no lethals in sight. This is a military station, our main military station, it makes zero sense for there to be ZERO lethal weapons.
:cl:
add: 3 Lasguns
add: 3 Tac-Eguns
add: 3 Shotguns
add: Shotgun Shells
add: Grenades
add: Handout Window
add: moved the disabler kits to a locker outside
add: Lieutenant NUMB NUTS!
add: Charlie. …

Casiostation Armory Improvement

---

_maps/map_files/Mining/Jungle.dmm

Minor Jungleplanet fixes, includes removing some planetgen and fixing wires as well as failing power.
This shit would not only always run out of power super fast but also had missing wires and some genturf.
Fixes all of that.
:cl:
fix: fixed power and generation issues on jungleplanet
/:cl:

Jungleplanet Minor Fixes

---

ModularBungalow/bungalow_beacon.dm

This has been on our to-do list forever. This adds a melter to the captain's list of guns.
This has been on the todo list forever. It will be a good rounding to the captain's kit for the time being.
:cl:
add: Added melter to the captain's gun lineup
/:cl:

Final Captain gun: L-204 Melter

---

ModularBungalow/medicine/virology/buffs.dm
ModularBungalow/medicine/virology/healing.dm
code/__DEFINES/atmospherics.dm

This PR does the following:
1) Nerfs all new symptoms to not be amazing
2) Miasma generation is doubled
Miasma was never seen, however our stations were always filled with gibs and corpses.
If this proves to be too much, we can always nerf it.
also, all the new symptoms were so good. This makes them slightly worse.
:cl:
tweak: doubled miasma generation
tweak: reduced stats on the new healing viruses.
/:cl:

Miasma generation increase and New Symptom fix

---

_maps/map_files/CasioStation/Casiostation.dmm

Adds the walkway back in casiostation.
Now the transport tube goes the whole way.
Fixes some issues with medical, and how they were missing some crucial things.
Also reduces the guns in the MP armory from 3 to 2, as there are only 2 MPs.
Just some minor bugfixes by the map's creator.
:cl:
tweak: reduced guns from 3 to 2 in the casiostation armory
tweak: added in the casiostation main hall again.
fix: fixed some issues with medical not having everything they need.
/:cl:

The Walkway

---

ModularBungalow/altjobtitles/outfits.dm

Expands Atmos tech outfits to include a bunch of the jumpsuits that we have.
Small little flavor for my favourite role.
:cl:
add: Added more atmos tech outfits
/:cl:

The Atmos Tech outfit expansion

---

ModularBungalow/bungalow_Weapons/Energy/sniper.dm
ModularBungalow/bungalow_Weapons/series/mining.dm
code/modules/projectiles/gun.dm

Reverts Bungalow-13/Bungalow-13#771

Revert "Adds Pinlocked Trait to Miner Guns"

---

ModularBungalow/bungalow_Weapons/Energy/sniper.dm
ModularBungalow/bungalow_Weapons/series/mining.dm
code/modules/projectiles/gun.dm

Reverts Bungalow-13/Bungalow-13#773

Revert "Revert "Adds Pinlocked Trait to Miner Guns""

---

_maps/map_files/RemoraStation/RemoraStation.dmm

adds oreboxes to the mining base
a tiny fan at the base and cargo(it was so easy to accidentally depressurize cargo)
and a catwalk to show where the mining base is!(to my knowledge, it wasn't marked at all)
:cl:
fix: Remora now has a few miner specific things that should have already existed
/:cl:

Remora now has oreboxes!

---

code/modules/research/designs/medical_designs.dm
code/modules/research/nanites/nanite_programs/healing.dm
code/modules/research/techweb/all_nodes.dm
code/modules/surgery/organs/heart.dm

Adds a nanite heart organ. Replaces your heart and allows for quicker nanite regen, but if you lose the nanites the heart breaks, then you have no heart. Because of the way emps work on nanites it would be nearly impossible to effectively remove them from someone so the heart adds 100 more flat emp nanite removal.
www.youtube.com/watch?v=RhMsboqMMzs
:cl:
add: Adds nanite heart from yogstation
/:cl:

Ports nanite heart from yogstation

---

code/modules/research/designs/medical_designs.dm

title
Sadie
:cl:
fix: nanite heart can now be printed
/:cl:

fixes nanite heart not being printable

---

code/modules/clothing/masks/gasmask.dm

title
its not fun having your gasmask burn up as a nukie 
:cl:
balance: the syndicate gasmask nolonger burns up
/:cl:

syndicate gasmasks nolonger burnup

---

code/modules/clothing/masks/gasmask.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm

title
:cl:
fix: snow legions nolonger die to snowstorms
/:cl:

snow legions nolonger die to snow storms

---

code/datums/chatmessage.dm
code/game/objects/structures/fluff.dm
code/modules/mob/living/carbon/alien/humanoid/queen.dm
code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/hostile/space_dragon.dm

port of https://github.com/BeeStation/BeeStation-Hornet/pull/6805
also ports https://github.com/tgstation/tgstation/pull/63848
for better runechat over the megafauna 
better tells, less instant killing
:cl:
balance: colossus now has tells to his attacks
/:cl:

[PORT] Colossus tells

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

title
you don't have to set it every game
:cl:
tweak: you can now set hair gradients in character setup
/:cl:

hair gradients in character setup

---

_maps/map_files/TaliStation/TaliStation.dmm

adds mirrors to the bathroom, removes the wall in science desk and adds a camera to xenobio cooler
:cl:
fix: talistation now has mirrors in the public bathroom, a camera in xenobio cooler, and nolonger has a wall hidden in the science desk
/:cl:

fixes some minor stuff with tali

---

code/modules/mob/living/emote.dm

all felinids laugh like cats
I want to make people suffer
:cl:
tweak: all felinids now laugh like cats
/:cl:

felinid buff

---

ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm
ModularTegustation/tegu_traitor_code/uplink_items_tegu.dm
code/__DEFINES/sound.dm
code/_compile_options.dm
code/modules/admin/verbs/commandreport.dm
code/modules/admin/verbs/randomverbs.dm
tgstation.dme
tgui/packages/tgui/interfaces/CommandReport.js
tgui/packages/tgui/interfaces/FakeCommandReport.js

Egor wanted this ported
you can find the linked PRs here
https://github.com/vlggms/tegustation/pull/142
cool traitor item and easier to use admin command

TGUI command reports

---

code/modules/reagents/chemistry/reagents/medicine_reagents.dm

this chem goes largely unused after the change, trading an already hard to heal damage into an even harder to heal damage
chem gets used again

un-nerfs pentetic acid

---

ModularBungalow/cargo/blackmarket.dm

fixes https://github.com/Quasar-13/Quasar-13/issues/785

blackmarket uplink now has right gun

---

code/game/objects/items/defib.dm

increased the doafter for harm intenting with EMPed defib
it now takes 5 seconds to give someone a heart attack instead of 1.5
your death is now slower, you're still gonna die

nerfs EMPed defib
